// <auto-generated />
using System;
using Liyanjie.FakeMQ;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Liyanjie.FakeMQ.Sample.AspNetCore_2_1.Migrations.FakeMQ
{
    [DbContext(typeof(FakeMQContext))]
    [Migration("20191102132336_000")]
    partial class _000
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Liyanjie.FakeMQ.FakeMQEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message");

                    b.Property<long>("Timestamp");

                    b.Property<string>("Type")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("FakeMQEvents");
                });

            modelBuilder.Entity("Liyanjie.FakeMQ.FakeMQProcess", b =>
                {
                    b.Property<string>("Subscription")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Timestamp");

                    b.HasKey("Subscription");

                    b.ToTable("FakeMQProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
