// <auto-generated />
using System;
using Liyanjie.FakeMQ;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Liyanjie.FakeMQ.Sample.AspNetCore.Migrations.FakeMQ
{
    [DbContext(typeof(FakeMQDbContext))]
    [Migration("20191102132702_000")]
    partial class _000
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Liyanjie.FakeMQ.FakeMQEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("FakeMQEvents");
                });

            modelBuilder.Entity("Liyanjie.FakeMQ.FakeMQProcess", b =>
                {
                    b.Property<string>("Subscription")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Subscription");

                    b.ToTable("FakeMQProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
